WARNING 08/28/2024 10:34:41 AM  * Debugger is active! _log
INFO 08/28/2024 10:34:41 AM  * Debugger PIN: 959-246-021 _log
INFO 08/28/2024 10:35:45 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_main.py', reloading _log
INFO 08/28/2024 10:35:45 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_main.py', reloading _log
INFO 08/28/2024 10:35:45 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_main.py', reloading _log
WARNING 08/28/2024 10:35:46 AM  * Debugger is active! _log
INFO 08/28/2024 10:35:46 AM  * Debugger PIN: 959-246-021 _log
INFO 08/28/2024 10:35:51 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_main.py', reloading _log
INFO 08/28/2024 10:35:51 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_main.py', reloading _log
INFO 08/28/2024 10:35:51 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_main.py', reloading _log
WARNING 08/28/2024 10:35:53 AM  * Debugger is active! _log
INFO 08/28/2024 10:35:53 AM  * Debugger PIN: 959-246-021 _log
INFO 08/28/2024 10:36:04 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_server.py', reloading _log
INFO 08/28/2024 10:36:04 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_server.py', reloading _log
WARNING 08/28/2024 10:36:08 AM  * Debugger is active! _log
INFO 08/28/2024 10:36:08 AM  * Debugger PIN: 959-246-021 _log
INFO 08/28/2024 10:36:18 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:36:18 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:36:18 AM  * Restarting with watchdog (windowsapi) _log
WARNING 08/28/2024 10:36:20 AM  * Debugger is active! _log
INFO 08/28/2024 10:36:20 AM  * Debugger PIN: 959-246-021 _log
ERROR 08/28/2024 10:36:35 AM get() missing 1 required positional argument: 'data' main
INFO 08/28/2024 10:36:35 AM 127.0.0.1 - - [28/Aug/2024 10:36:35] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 10:36:50 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_server.py', reloading _log
INFO 08/28/2024 10:36:50 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_server.py', reloading _log
INFO 08/28/2024 10:36:50 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_server.py', reloading _log
INFO 08/28/2024 10:36:51 AM  * Restarting with watchdog (windowsapi) _log
WARNING 08/28/2024 10:36:53 AM  * Debugger is active! _log
INFO 08/28/2024 10:36:53 AM  * Debugger PIN: 959-246-021 _log
INFO 08/28/2024 10:36:54 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_server.py', reloading _log
INFO 08/28/2024 10:36:54 AM  * Detected change in 'c:\\Users\\rachid.h.elihimas\\Desktop\\cial\\app\\stock_server.py', reloading _log
INFO 08/28/2024 10:36:54 AM  * Restarting with watchdog (windowsapi) _log
WARNING 08/28/2024 10:36:56 AM  * Debugger is active! _log
INFO 08/28/2024 10:36:56 AM  * Debugger PIN: 959-246-021 _log
INFO 08/28/2024 10:36:59 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:36:59 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:36:59 AM  * Restarting with watchdog (windowsapi) _log
WARNING 08/28/2024 10:37:01 AM  * Debugger is active! _log
INFO 08/28/2024 10:37:01 AM  * Debugger PIN: 959-246-021 _log
ERROR 08/28/2024 10:37:12 AM get() missing 1 required positional argument: 'data' main
INFO 08/28/2024 10:37:13 AM  * Detected change in 'C:\\Users\\rachid.h.elihimas\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\json\\provider.py', reloading _log
INFO 08/28/2024 10:37:13 AM  * Detected change in 'C:\\Users\\rachid.h.elihimas\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py', reloading _log
INFO 08/28/2024 10:37:13 AM  * Detected change in 'C:\\Users\\rachid.h.elihimas\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\encoder.py', reloading _log
INFO 08/28/2024 10:37:13 AM 127.0.0.1 - - [28/Aug/2024 10:37:13] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 10:37:13 AM  * Restarting with watchdog (windowsapi) _log
WARNING 08/28/2024 10:37:15 AM  * Debugger is active! _log
INFO 08/28/2024 10:37:15 AM  * Debugger PIN: 959-246-021 _log
INFO 08/28/2024 10:38:08 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:38:08 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:38:08 AM  * Restarting with watchdog (windowsapi) _log
INFO 08/28/2024 10:39:32 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:39:32 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:39:32 AM  * Restarting with watchdog (windowsapi) _log
INFO 08/28/2024 10:39:43 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:39:43 AM [33mPress CTRL+C to quit[0m _log
ERROR 08/28/2024 10:39:49 AM get() missing 1 required positional argument: 'data' main
ERROR 08/28/2024 10:39:49 AM Exception on /stock/aapl [GET] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 18, in get_stock
    return jsonify({service})
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
INFO 08/28/2024 10:39:49 AM 127.0.0.1 - - [28/Aug/2024 10:39:49] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 10:40:09 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:40:09 AM [33mPress CTRL+C to quit[0m _log
ERROR 08/28/2024 10:40:57 AM get() missing 1 required positional argument: 'data' main
ERROR 08/28/2024 10:40:57 AM Exception on /stock/aapl [GET] log_exception
Traceback (most recent call last):
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 18, in get_stock
    return jsonify({service})
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
INFO 08/28/2024 10:40:57 AM 127.0.0.1 - - [28/Aug/2024 10:40:57] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
ERROR 08/28/2024 10:41:14 AM get() missing 1 required positional argument: 'data' main
INFO 08/28/2024 10:41:29 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:41:29 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:41:37 AM Starting GET method get
INFO 08/28/2024 10:41:37 AM Polygon data extraction polygon
ERROR 08/28/2024 10:41:37 AM name 'date' is not defined polygon
INFO 08/28/2024 10:41:37 AM Starting WebScraping on MarketWatch for stock aapl stock_martketwatch
ERROR 08/28/2024 10:42:18 AM Error during data extraction from MarketWatch - 'NoneType' object has no attribute 'inner_text' stock_martketwatch
ERROR 08/28/2024 10:42:18 AM 'NameError' object is not subscriptable get
ERROR 08/28/2024 10:42:24 AM Exception on /stock/aapl [GET] log_exception
Traceback (most recent call last):
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 18, in get_stock
    return jsonify({service})
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
INFO 08/28/2024 10:42:24 AM 127.0.0.1 - - [28/Aug/2024 10:42:24] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 10:43:31 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:43:31 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:43:48 AM Starting GET method get
INFO 08/28/2024 10:43:51 AM Polygon data extraction polygon
ERROR 08/28/2024 10:43:51 AM name 'date' is not defined polygon
INFO 08/28/2024 10:45:30 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:45:30 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:46:26 AM Starting GET method get
INFO 08/28/2024 10:46:28 AM Polygon data extraction polygon
INFO 08/28/2024 10:46:32 AM Formatting date formatador_data
INFO 08/28/2024 10:47:03 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:47:03 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:47:19 AM Starting GET method get
INFO 08/28/2024 10:47:20 AM Polygon data extraction polygon
INFO 08/28/2024 10:47:23 AM Formatting date formatador_data
INFO 08/28/2024 10:47:23 AM Date formatted with success formatador_data
INFO 08/28/2024 10:47:28 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 10:47:28 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 10:47:42 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"458821dabb514a95f3c3d2ff9161ac79","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 10:47:46 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"458821dabb514a95f3c3d2ff9161ac79","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 10:47:54 AM 'Exception' object is not subscriptable get
ERROR 08/28/2024 10:47:57 AM Exception on /stock/aapl [GET] log_exception
Traceback (most recent call last):
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 18, in get_stock
    return jsonify({service})
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
INFO 08/28/2024 10:47:57 AM 127.0.0.1 - - [28/Aug/2024 10:47:57] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 10:48:36 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:48:36 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:48:43 AM Starting GET method get
INFO 08/28/2024 10:48:44 AM Polygon data extraction polygon
INFO 08/28/2024 10:48:46 AM Formatting date formatador_data
INFO 08/28/2024 10:48:46 AM Date formatted with success formatador_data
INFO 08/28/2024 10:48:48 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 10:48:48 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 10:49:43 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"efa6acc78392c839cf4b5b28e804bd17","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 10:50:05 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"efa6acc78392c839cf4b5b28e804bd17","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
INFO 08/28/2024 10:53:20 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:53:20 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:53:29 AM Starting GET method get
INFO 08/28/2024 10:53:29 AM Polygon data extraction polygon
INFO 08/28/2024 10:53:31 AM Formatting date formatador_data
INFO 08/28/2024 10:53:31 AM Date formatted with success formatador_data
INFO 08/28/2024 10:53:33 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 10:53:33 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 10:53:39 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"2a351fd15a054d85f4d83f9961f5a8c7","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 10:53:43 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"2a351fd15a054d85f4d83f9961f5a8c7","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 10:53:57 AM None get
ERROR 08/28/2024 10:54:02 AM Exception on /stock/aapl [GET] log_exception
Traceback (most recent call last):
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 18, in get_stock
    return jsonify({service})
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
INFO 08/28/2024 10:54:02 AM 127.0.0.1 - - [28/Aug/2024 10:54:02] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 10:55:45 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:55:45 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:55:54 AM Starting GET method get
INFO 08/28/2024 10:55:55 AM Polygon data extraction polygon
INFO 08/28/2024 10:55:56 AM Formatting date formatador_data
INFO 08/28/2024 10:55:56 AM Date formatted with success formatador_data
INFO 08/28/2024 10:55:57 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 10:55:57 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 10:56:06 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"24ec1b32cab9b431ebd2436b881a33cc","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 10:56:09 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"24ec1b32cab9b431ebd2436b881a33cc","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 10:56:19 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"24ec1b32cab9b431ebd2436b881a33cc","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' get
INFO 08/28/2024 10:58:06 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 10:58:06 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 10:58:13 AM Starting GET method get
INFO 08/28/2024 10:58:14 AM Polygon data extraction polygon
INFO 08/28/2024 10:58:16 AM Formatting date formatador_data
INFO 08/28/2024 10:58:16 AM Date formatted with success formatador_data
INFO 08/28/2024 10:58:17 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 10:58:17 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 10:58:28 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"f9a9c74283f52eefddc66ddbb738632c","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 10:58:31 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"f9a9c74283f52eefddc66ddbb738632c","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 10:58:39 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"f9a9c74283f52eefddc66ddbb738632c","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' get
ERROR 08/28/2024 10:58:53 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"f9a9c74283f52eefddc66ddbb738632c","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' main
INFO 08/28/2024 11:00:42 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:00:42 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:00:48 AM Starting GET method get
INFO 08/28/2024 11:00:48 AM Polygon data extraction polygon
INFO 08/28/2024 11:00:48 AM Formatting date formatador_data
INFO 08/28/2024 11:00:48 AM Date formatted with success formatador_data
INFO 08/28/2024 11:00:48 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:00:48 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 11:00:51 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"40e57ea4c0c7f9700f6232d5ce611eb3","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 11:00:51 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"40e57ea4c0c7f9700f6232d5ce611eb3","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 11:00:53 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"40e57ea4c0c7f9700f6232d5ce611eb3","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' get
ERROR 08/28/2024 11:00:56 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"40e57ea4c0c7f9700f6232d5ce611eb3","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' main
ERROR 08/28/2024 11:00:56 AM Exception on /stock/aapl [GET] log_exception
Traceback (most recent call last):
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 22, in get_stock
    return jsonify({'Retorno': service})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Exception is not JSON serializable
INFO 08/28/2024 11:00:56 AM 127.0.0.1 - - [28/Aug/2024 11:00:56] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 11:01:40 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:01:40 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:01:51 AM Starting GET method get
INFO 08/28/2024 11:01:51 AM Polygon data extraction polygon
INFO 08/28/2024 11:01:51 AM Formatting date formatador_data
INFO 08/28/2024 11:01:51 AM Date formatted with success formatador_data
INFO 08/28/2024 11:01:51 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:01:51 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 11:01:51 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"a4afe190c23480a8d42ecbfc21a30f23","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 11:01:51 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"a4afe190c23480a8d42ecbfc21a30f23","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 11:01:51 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"a4afe190c23480a8d42ecbfc21a30f23","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' get
ERROR 08/28/2024 11:01:51 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"a4afe190c23480a8d42ecbfc21a30f23","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' main
INFO 08/28/2024 11:02:13 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:02:13 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:02:17 AM Starting GET method get
INFO 08/28/2024 11:02:17 AM Polygon data extraction polygon
INFO 08/28/2024 11:02:17 AM Formatting date formatador_data
INFO 08/28/2024 11:02:17 AM Date formatted with success formatador_data
INFO 08/28/2024 11:02:17 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:02:17 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 11:02:17 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"8ce0cc6fb63ae183b39762465ad3b964","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 11:02:17 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"8ce0cc6fb63ae183b39762465ad3b964","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 11:02:17 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"8ce0cc6fb63ae183b39762465ad3b964","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' get
ERROR 08/28/2024 11:02:17 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"8ce0cc6fb63ae183b39762465ad3b964","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' main
ERROR 08/28/2024 11:02:21 AM Exception on /stock/aapl [GET] log_exception
Traceback (most recent call last):
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 20, in get_stock
    return jsonify({'error': service[1]}), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Exception is not JSON serializable
INFO 08/28/2024 11:02:21 AM 127.0.0.1 - - [28/Aug/2024 11:02:21] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 11:04:06 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:04:06 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:04:08 AM Starting GET method get
INFO 08/28/2024 11:04:08 AM Polygon data extraction polygon
INFO 08/28/2024 11:04:08 AM Formatting date formatador_data
INFO 08/28/2024 11:04:08 AM Date formatted with success formatador_data
INFO 08/28/2024 11:04:08 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:04:08 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 11:04:09 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"cfc7e5e528ee703814515d3aac60a2a1","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 11:04:09 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"cfc7e5e528ee703814515d3aac60a2a1","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' polygon
ERROR 08/28/2024 11:04:09 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"cfc7e5e528ee703814515d3aac60a2a1","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' get
ERROR 08/28/2024 11:04:09 AM Error on the data extraction from Polygon - 403 - {"status":"NOT_AUTHORIZED","request_id":"cfc7e5e528ee703814515d3aac60a2a1","message":"Attempted to request today's data before end of day. Please upgrade your plan at https://polygon.io/pricing"}' main
INFO 08/28/2024 11:04:09 AM 127.0.0.1 - - [28/Aug/2024 11:04:09] "[33mGET /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/28/2024 11:07:50 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:07:50 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:07:56 AM Starting GET method get
INFO 08/28/2024 11:07:56 AM Polygon data extraction polygon
INFO 08/28/2024 11:07:56 AM Formatting date formatador_data
INFO 08/28/2024 11:07:56 AM Date formatted with success formatador_data
INFO 08/28/2024 11:07:56 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:07:56 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 11:07:57 AM string indices must be integers, not 'str' get
ERROR 08/28/2024 11:07:57 AM string indices must be integers, not 'str' main
INFO 08/28/2024 11:07:57 AM 127.0.0.1 - - [28/Aug/2024 11:07:57] "[33mGET /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/28/2024 11:08:26 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:08:26 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:08:40 AM Starting GET method get
INFO 08/28/2024 11:08:41 AM Polygon data extraction polygon
INFO 08/28/2024 11:08:41 AM Formatting date formatador_data
INFO 08/28/2024 11:08:41 AM Date formatted with success formatador_data
INFO 08/28/2024 11:08:41 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:08:41 AM Informed date is between Monday and Friday verificar_fim_de_semana
ERROR 08/28/2024 11:09:14 AM string indices must be integers, not 'str' get
ERROR 08/28/2024 11:09:14 AM string indices must be integers, not 'str' main
INFO 08/28/2024 11:09:17 AM 127.0.0.1 - - [28/Aug/2024 11:09:17] "[33mGET /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/28/2024 11:09:33 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:09:33 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:09:41 AM Starting GET method get
INFO 08/28/2024 11:09:42 AM Polygon data extraction polygon
INFO 08/28/2024 11:09:42 AM Formatting date formatador_data
INFO 08/28/2024 11:09:42 AM Date formatted with success formatador_data
INFO 08/28/2024 11:09:42 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:09:42 AM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 11:10:25 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:10:25 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:10:30 AM Starting GET method get
INFO 08/28/2024 11:10:30 AM Polygon data extraction polygon
INFO 08/28/2024 11:10:30 AM Formatting date formatador_data
INFO 08/28/2024 11:10:30 AM Date formatted with success formatador_data
INFO 08/28/2024 11:10:30 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:10:30 AM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 11:11:15 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:11:15 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:11:22 AM Starting GET method get
INFO 08/28/2024 11:11:22 AM Polygon data extraction polygon
INFO 08/28/2024 11:11:22 AM Formatting date formatador_data
INFO 08/28/2024 11:11:22 AM Date formatted with success formatador_data
INFO 08/28/2024 11:11:22 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:11:22 AM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 11:11:33 AM Finishing GET method and returning data get
ERROR 08/28/2024 11:11:45 AM Exception on /stock/aapl [GET] log_exception
Traceback (most recent call last):
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 18, in get_stock
    if not service[0]:
           ~~~~~~~^^^
KeyError: 0
INFO 08/28/2024 11:11:45 AM 127.0.0.1 - - [28/Aug/2024 11:11:45] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 11:12:14 AM Starting GET method get
INFO 08/28/2024 11:12:14 AM Polygon data extraction polygon
INFO 08/28/2024 11:12:14 AM Formatting date formatador_data
INFO 08/28/2024 11:12:14 AM Date formatted with success formatador_data
INFO 08/28/2024 11:12:14 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:12:14 AM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 11:12:17 AM Finishing GET method and returning data get
INFO 08/28/2024 11:12:43 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:12:43 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:12:53 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:12:53 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:12:59 AM Starting GET method get
INFO 08/28/2024 11:12:59 AM Polygon data extraction polygon
INFO 08/28/2024 11:12:59 AM Formatting date formatador_data
INFO 08/28/2024 11:12:59 AM Date formatted with success formatador_data
INFO 08/28/2024 11:12:59 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:12:59 AM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 11:13:00 AM Finishing GET method and returning data get
INFO 08/28/2024 11:13:04 AM 127.0.0.1 - - [28/Aug/2024 11:13:04] "GET /stock/aapl HTTP/1.1" 200 - _log
INFO 08/28/2024 11:13:51 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:13:51 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:14:01 AM Starting GET method get
INFO 08/28/2024 11:14:01 AM Polygon data extraction polygon
INFO 08/28/2024 11:14:01 AM Formatting date formatador_data
INFO 08/28/2024 11:14:01 AM Date formatted with success formatador_data
INFO 08/28/2024 11:14:01 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:14:01 AM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 11:14:01 AM Finishing GET method and returning data get
INFO 08/28/2024 11:14:01 AM 127.0.0.1 - - [28/Aug/2024 11:14:01] "GET /stock/aapl HTTP/1.1" 200 - _log
INFO 08/28/2024 11:14:22 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:14:22 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:14:24 AM Starting GET method get
INFO 08/28/2024 11:14:24 AM Polygon data extraction polygon
INFO 08/28/2024 11:14:24 AM Formatting date formatador_data
INFO 08/28/2024 11:14:24 AM Date formatted with success formatador_data
INFO 08/28/2024 11:14:24 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:14:24 AM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 11:14:24 AM Finishing GET method and returning data get
ERROR 08/28/2024 11:14:24 AM Exception on /stock/aapl [GET] log_exception
Traceback (most recent call last):
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 21, in get_stock
    return jsonify({service[1]})
                   ^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
INFO 08/28/2024 11:14:24 AM 127.0.0.1 - - [28/Aug/2024 11:14:24] "[35m[1mGET /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 11:16:58 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:16:58 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:18:35 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:18:35 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:18:41 AM Starting GET method get
INFO 08/28/2024 11:18:41 AM Polygon data extraction polygon
INFO 08/28/2024 11:18:41 AM Formatting date formatador_data
INFO 08/28/2024 11:18:41 AM Date formatted with success formatador_data
INFO 08/28/2024 11:18:41 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 11:18:41 AM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 11:18:42 AM Finishing GET method and returning data get
INFO 08/28/2024 11:18:42 AM 127.0.0.1 - - [28/Aug/2024 11:18:42] "GET /stock/aapl HTTP/1.1" 200 - _log
INFO 08/28/2024 11:27:28 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 11:27:28 AM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 11:27:43 AM Starting main function main
INFO 08/28/2024 11:27:43 AM Post process main
INFO 08/28/2024 11:27:43 AM Finishing Post process main
INFO 08/28/2024 11:27:46 AM 127.0.0.1 - - [28/Aug/2024 11:27:46] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 201 - _log
INFO 08/28/2024 02:45:11 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 03:22:21 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 03:22:32 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 03:22:32 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 03:22:32 PM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 03:22:39 PM Starting main function main
INFO 08/28/2024 03:22:39 PM Get process main
INFO 08/28/2024 03:22:39 PM Starting GET method get
INFO 08/28/2024 03:22:39 PM Polygon data extraction polygon
INFO 08/28/2024 03:22:39 PM Formatting date formatador_data
INFO 08/28/2024 03:22:39 PM Date formatted with success formatador_data
INFO 08/28/2024 03:22:39 PM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 03:22:39 PM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 03:22:40 PM Finishing GET method and returning data get
INFO 08/28/2024 03:22:40 PM Finishing Get process main
INFO 08/28/2024 03:22:40 PM 127.0.0.1 - - [28/Aug/2024 15:22:40] "GET /stock/aapl HTTP/1.1" 200 - _log
INFO 08/28/2024 03:24:19 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 03:24:19 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 03:24:19 PM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 03:24:27 PM Starting main function main
INFO 08/28/2024 03:24:27 PM Get process main
INFO 08/28/2024 03:24:27 PM Starting GET method get
INFO 08/28/2024 03:24:27 PM Polygon data extraction polygon
INFO 08/28/2024 03:24:27 PM Formatting date formatador_data
INFO 08/28/2024 03:24:27 PM Date formatted with success formatador_data
INFO 08/28/2024 03:24:27 PM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 03:24:27 PM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 03:24:27 PM Finishing GET method and returning data get
INFO 08/28/2024 03:24:27 PM Finishing Get process main
INFO 08/28/2024 03:24:27 PM 127.0.0.1 - - [28/Aug/2024 15:24:27] "GET /stock/aapl HTTP/1.1" 200 - _log
INFO 08/28/2024 04:02:33 PM 127.0.0.1 - - [28/Aug/2024 16:02:33] "[31m[1mPOST /stock/aapl HTTP/1.1[0m" 400 - _log
INFO 08/28/2024 04:02:44 PM 127.0.0.1 - - [28/Aug/2024 16:02:44] "[31m[1mPOST /stock/aapl HTTP/1.1[0m" 400 - _log
INFO 08/28/2024 04:03:09 PM 127.0.0.1 - - [28/Aug/2024 16:03:09] "[31m[1mPOST /stock/aapl HTTP/1.1[0m" 400 - _log
INFO 08/28/2024 04:30:59 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:32:14 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:32:50 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:33:03 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:33:16 PM Data inserted to Postgres Database successfully database_operation
INFO 08/28/2024 04:33:38 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:33:48 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:34:30 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:34:36 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:36:05 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:36:11 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:36:15 PM Data inserted to Postgres Database successfully database_operation
INFO 08/28/2024 04:36:29 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:36:38 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:37:09 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:37:14 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:37:43 PM Data inserted to Postgres Database successfully database_operation
INFO 08/28/2024 04:38:33 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:38:35 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:38:50 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:38:53 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:38:59 PM Data inserted to Postgres Database successfully database_operation
INFO 08/28/2024 04:39:15 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:39:17 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:41:08 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:41:14 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 04:41:16 PM Data inserted to Postgres Database successfully insert_amount
INFO 08/28/2024 04:41:20 PM Data inserted to Postgres Database successfully database_operation
INFO 08/28/2024 04:41:35 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:42:19 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:43:00 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:43:21 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:44:10 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:44:24 PM Inserting data into Postgres Database update_amount
INFO 08/28/2024 04:44:29 PM Data inserted to Postgres Database successfully database_operation
INFO 08/28/2024 04:44:52 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:44:58 PM Inserting data into Postgres Database update_amount
INFO 08/28/2024 04:45:05 PM Stock TESTE updated successfully with new amount 20.0 update_amount
ERROR 08/28/2024 04:51:04 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:51:04 PM 127.0.0.1 - - [28/Aug/2024 16:51:04] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
ERROR 08/28/2024 04:51:14 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'float' has no len()
INFO 08/28/2024 04:51:14 PM 127.0.0.1 - - [28/Aug/2024 16:51:14] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 04:51:28 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 04:51:48 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 04:51:48 PM [33mPress CTRL+C to quit[0m _log
ERROR 08/28/2024 04:51:56 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'float' has no len()
INFO 08/28/2024 04:51:56 PM 127.0.0.1 - - [28/Aug/2024 16:51:56] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
ERROR 08/28/2024 04:52:01 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'float' has no len()
INFO 08/28/2024 04:52:01 PM 127.0.0.1 - - [28/Aug/2024 16:52:01] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 04:52:03 PM Starting main function main
INFO 08/28/2024 04:52:03 PM Get process main
INFO 08/28/2024 04:52:03 PM Starting GET method get
INFO 08/28/2024 04:52:03 PM Polygon data extraction polygon
INFO 08/28/2024 04:52:03 PM Formatting date formatador_data
INFO 08/28/2024 04:52:03 PM Date formatted with success formatador_data
INFO 08/28/2024 04:52:03 PM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 04:52:03 PM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 04:52:06 PM Finishing GET method and returning data get
INFO 08/28/2024 04:52:06 PM Finishing Get process main
INFO 08/28/2024 04:52:06 PM 127.0.0.1 - - [28/Aug/2024 16:52:06] "GET /stock/aapl HTTP/1.1" 200 - _log
ERROR 08/28/2024 04:52:19 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'float' has no len()
INFO 08/28/2024 04:52:19 PM 127.0.0.1 - - [28/Aug/2024 16:52:19] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
ERROR 08/28/2024 04:52:45 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:52:45 PM 127.0.0.1 - - [28/Aug/2024 16:52:45] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 04:53:15 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 04:53:15 PM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 04:53:15 PM  * Restarting with watchdog (windowsapi) _log
INFO 08/28/2024 04:53:42 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 04:53:42 PM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 04:53:42 PM  * Restarting with watchdog (windowsapi) _log
INFO 08/28/2024 04:53:58 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 04:53:58 PM [33mPress CTRL+C to quit[0m _log
ERROR 08/28/2024 04:54:01 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:54:01 PM 127.0.0.1 - - [28/Aug/2024 16:54:01] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
ERROR 08/28/2024 04:54:37 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:54:37 PM 127.0.0.1 - - [28/Aug/2024 16:54:37] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
ERROR 08/28/2024 04:55:01 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:55:01 PM 127.0.0.1 - - [28/Aug/2024 16:55:01] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 04:55:03 PM Starting main function main
INFO 08/28/2024 04:55:03 PM Get process main
INFO 08/28/2024 04:55:03 PM Starting GET method get
INFO 08/28/2024 04:55:03 PM Polygon data extraction polygon
INFO 08/28/2024 04:55:03 PM Formatting date formatador_data
INFO 08/28/2024 04:55:03 PM Date formatted with success formatador_data
INFO 08/28/2024 04:55:03 PM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 04:55:03 PM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 04:55:05 PM Finishing GET method and returning data get
INFO 08/28/2024 04:55:05 PM Finishing Get process main
INFO 08/28/2024 04:55:05 PM 127.0.0.1 - - [28/Aug/2024 16:55:05] "GET /stock/aapl HTTP/1.1" 200 - _log
ERROR 08/28/2024 04:56:14 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:56:14 PM 127.0.0.1 - - [28/Aug/2024 16:56:14] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
ERROR 08/28/2024 04:56:31 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:56:31 PM 127.0.0.1 - - [28/Aug/2024 16:56:31] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 04:56:38 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 04:56:38 PM [33mPress CTRL+C to quit[0m _log
ERROR 08/28/2024 04:56:45 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:56:45 PM 127.0.0.1 - - [28/Aug/2024 16:56:45] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
ERROR 08/28/2024 04:56:47 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:56:47 PM 127.0.0.1 - - [28/Aug/2024 16:56:47] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
ERROR 08/28/2024 04:56:48 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:56:48 PM 127.0.0.1 - - [28/Aug/2024 16:56:48] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 04:58:38 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 04:58:38 PM [33mPress CTRL+C to quit[0m _log
ERROR 08/28/2024 04:58:41 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
    try:
       ^^
TypeError: object of type 'int' has no len()
INFO 08/28/2024 04:58:41 PM 127.0.0.1 - - [28/Aug/2024 16:58:41] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 04:58:48 PM Starting main function main
INFO 08/28/2024 04:58:48 PM Get process main
INFO 08/28/2024 04:58:48 PM Starting GET method get
INFO 08/28/2024 04:58:48 PM Polygon data extraction polygon
INFO 08/28/2024 04:58:48 PM Formatting date formatador_data
INFO 08/28/2024 04:58:48 PM Date formatted with success formatador_data
INFO 08/28/2024 04:58:48 PM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/28/2024 04:58:48 PM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/28/2024 04:58:49 PM Finishing GET method and returning data get
INFO 08/28/2024 04:58:49 PM Finishing Get process main
INFO 08/28/2024 04:58:49 PM 127.0.0.1 - - [28/Aug/2024 16:58:49] "GET /stock/aapl HTTP/1.1" 200 - _log
INFO 08/28/2024 04:59:56 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 04:59:56 PM [33mPress CTRL+C to quit[0m _log
ERROR 08/28/2024 05:00:06 PM Exception on /stock/aapl [POST] log_exception
Traceback (most recent call last):
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rachid.h.elihimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rachid.h.elihimas\Desktop\cial\app\stock_server.py", line 30, in update_stock
    try:
       ^^
TypeError: object of type 'int' has no len()
INFO 08/28/2024 05:00:06 PM 127.0.0.1 - - [28/Aug/2024 17:00:06] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 500 - _log
INFO 08/28/2024 05:02:01 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 05:02:01 PM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 05:02:11 PM Starting main function main
INFO 08/28/2024 05:02:11 PM Post process main
INFO 08/28/2024 05:02:11 PM Starting POST method post
INFO 08/28/2024 05:02:13 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 05:02:17 PM Verifying if Stock already exists on the database check_stock
ERROR 08/28/2024 05:02:18 PM 'TypeError' object is not subscriptable post
ERROR 08/28/2024 05:02:18 PM 'TypeError' object is not subscriptable main
INFO 08/28/2024 05:02:18 PM 127.0.0.1 - - [28/Aug/2024 17:02:18] "[33mPOST /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/28/2024 05:03:05 PM Starting main function main
INFO 08/28/2024 05:03:05 PM Post process main
INFO 08/28/2024 05:03:05 PM Starting POST method post
INFO 08/28/2024 05:03:19 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 05:03:24 PM Verifying if Stock already exists on the database check_stock
INFO 08/28/2024 05:04:18 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 05:04:18 PM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 05:04:27 PM Starting main function main
INFO 08/28/2024 05:04:27 PM Post process main
INFO 08/28/2024 05:04:27 PM Starting POST method post
INFO 08/28/2024 05:04:30 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 05:04:34 PM Verifying if Stock already exists on the database check_stock
ERROR 08/28/2024 05:05:19 PM 'TypeError' object is not subscriptable post
ERROR 08/28/2024 05:05:19 PM 'TypeError' object is not subscriptable main
INFO 08/28/2024 05:05:19 PM 127.0.0.1 - - [28/Aug/2024 17:05:19] "[33mPOST /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/28/2024 05:05:24 PM Starting main function main
INFO 08/28/2024 05:05:24 PM Post process main
INFO 08/28/2024 05:05:24 PM Starting POST method post
INFO 08/28/2024 05:05:29 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 05:05:33 PM Verifying if Stock already exists on the database check_stock
ERROR 08/28/2024 05:08:51 PM 'TypeError' object is not subscriptable post
ERROR 08/28/2024 05:08:51 PM 'TypeError' object is not subscriptable main
INFO 08/28/2024 05:08:51 PM 127.0.0.1 - - [28/Aug/2024 17:08:51] "[33mPOST /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/28/2024 05:09:00 PM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/28/2024 05:09:00 PM [33mPress CTRL+C to quit[0m _log
INFO 08/28/2024 05:09:12 PM Starting main function main
INFO 08/28/2024 05:09:12 PM Post process main
INFO 08/28/2024 05:09:12 PM Starting POST method post
INFO 08/28/2024 05:09:14 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 05:09:14 PM Verifying if Stock already exists on the database check_stock
INFO 08/28/2024 05:09:14 PM Verification complete check_stock
INFO 08/28/2024 05:09:14 PM Inserting data into Postgres Database update_amount
INFO 08/28/2024 05:09:14 PM Stock TESTE updated successfully with new amount 30.0 update_amount
INFO 08/28/2024 05:09:14 PM Data updated to Postgres Database successfully database_operation
INFO 08/28/2024 05:09:14 PM Starting POST method and returning data post
INFO 08/28/2024 05:09:14 PM Finishing Post process main
INFO 08/28/2024 05:09:14 PM 127.0.0.1 - - [28/Aug/2024 17:09:14] "[35m[1mPOST /stock/teste HTTP/1.1[0m" 201 - _log
INFO 08/28/2024 05:09:27 PM Starting main function main
INFO 08/28/2024 05:09:27 PM Post process main
INFO 08/28/2024 05:09:27 PM Starting POST method post
INFO 08/28/2024 05:09:28 PM Connection to Postgres Database successful database_operation
INFO 08/28/2024 05:09:28 PM Verifying if Stock already exists on the database check_stock
INFO 08/28/2024 05:09:29 PM Inserting data into Postgres Database insert_amount
INFO 08/28/2024 05:09:29 PM Data inserted to Postgres Database successfully insert_amount
INFO 08/28/2024 05:09:29 PM Data inserted to Postgres Database successfully database_operation
INFO 08/28/2024 05:09:29 PM Starting POST method and returning data post
INFO 08/28/2024 05:09:29 PM Finishing Post process main
INFO 08/28/2024 05:09:29 PM 127.0.0.1 - - [28/Aug/2024 17:09:29] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 201 - _log
INFO 08/29/2024 08:29:27 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/29/2024 08:29:27 AM [33mPress CTRL+C to quit[0m _log
ERROR 08/29/2024 08:29:35 AM False main
INFO 08/29/2024 08:29:35 AM 127.0.0.1 - - [29/Aug/2024 08:29:35] "[33mGET /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/29/2024 08:29:38 AM 127.0.0.1 - - [29/Aug/2024 08:29:38] "[33mGET /stock/aaplaa HTTP/1.1[0m" 404 - _log
INFO 08/29/2024 08:29:56 AM 127.0.0.1 - - [29/Aug/2024 08:29:56] "[33mGET /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/29/2024 08:30:07 AM 127.0.0.1 - - [29/Aug/2024 08:30:07] "[33mGET /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/29/2024 08:30:16 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/29/2024 08:30:16 AM [33mPress CTRL+C to quit[0m _log
ERROR 08/29/2024 08:30:46 AM False main
INFO 08/29/2024 08:30:46 AM 127.0.0.1 - - [29/Aug/2024 08:30:46] "[33mGET /stock/aapl HTTP/1.1[0m" 404 - _log
INFO 08/29/2024 08:32:28 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/29/2024 08:32:28 AM [33mPress CTRL+C to quit[0m _log
INFO 08/29/2024 08:32:39 AM Starting main function main
INFO 08/29/2024 08:32:39 AM Get process main
INFO 08/29/2024 08:32:39 AM Starting GET method get
INFO 08/29/2024 08:32:39 AM Polygon data extraction polygon
INFO 08/29/2024 08:32:39 AM Formatting date formatador_data
INFO 08/29/2024 08:32:39 AM Date formatted with success formatador_data
INFO 08/29/2024 08:32:39 AM Verifying if date is a weekday. verificar_fim_de_semana
INFO 08/29/2024 08:32:39 AM Informed date is between Monday and Friday verificar_fim_de_semana
INFO 08/29/2024 08:32:40 AM Finishing GET method and returning data get
INFO 08/29/2024 08:32:40 AM Finishing Get process main
INFO 08/29/2024 08:32:40 AM 127.0.0.1 - - [29/Aug/2024 08:32:40] "GET /stock/aapl HTTP/1.1" 200 - _log
INFO 08/29/2024 08:32:47 AM 127.0.0.1 - - [29/Aug/2024 08:32:47] "GET /stock/aaplaa HTTP/1.1" 200 - _log
INFO 08/29/2024 08:32:50 AM 127.0.0.1 - - [29/Aug/2024 08:32:50] "GET /stock/aaplaa HTTP/1.1" 200 - _log
ERROR 08/29/2024 08:33:03 AM False main
INFO 08/29/2024 08:33:03 AM 127.0.0.1 - - [29/Aug/2024 08:33:03] "[33mPOST /stock/aaplaa HTTP/1.1[0m" 404 - _log
INFO 08/29/2024 08:33:35 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/29/2024 08:33:35 AM [33mPress CTRL+C to quit[0m _log
ERROR 08/29/2024 08:33:37 AM Stock name is not valid. main
INFO 08/29/2024 08:33:37 AM 127.0.0.1 - - [29/Aug/2024 08:33:37] "[33mGET /stock/aaplaa HTTP/1.1[0m" 404 - _log
INFO 08/29/2024 08:39:40 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/29/2024 08:39:40 AM [33mPress CTRL+C to quit[0m _log
INFO 08/29/2024 08:39:52 AM Starting main function main
INFO 08/29/2024 08:39:52 AM Post process main
INFO 08/29/2024 08:39:52 AM Starting POST method post
INFO 08/29/2024 08:39:53 AM Connection to Postgres Database successful database_operation
INFO 08/29/2024 08:39:59 AM Verifying if Stock already exists on the database check_stock
INFO 08/29/2024 08:40:02 AM Inserting data into Postgres Database insert_amount
INFO 08/29/2024 08:40:02 AM Data inserted to Postgres Database successfully insert_amount
INFO 08/29/2024 08:40:02 AM Data inserted to Postgres Database successfully database_operation
INFO 08/29/2024 08:40:02 AM Starting POST method and returning data post
INFO 08/29/2024 08:40:05 AM Finishing Post process main
INFO 08/29/2024 08:40:05 AM 127.0.0.1 - - [29/Aug/2024 08:40:05] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 201 - _log
INFO 08/29/2024 08:42:11 AM Starting main function main
INFO 08/29/2024 08:42:11 AM Post process main
INFO 08/29/2024 08:42:11 AM Starting POST method post
INFO 08/29/2024 08:42:12 AM Connection to Postgres Database successful database_operation
INFO 08/29/2024 08:42:12 AM Verifying if Stock already exists on the database check_stock
INFO 08/29/2024 08:42:12 AM Verification complete check_stock
INFO 08/29/2024 08:42:16 AM Inserting data into Postgres Database update_amount
INFO 08/29/2024 08:42:19 AM Stock AAPL updated successfully with new amount 20.0 update_amount
INFO 08/29/2024 08:42:19 AM Data updated to Postgres Database successfully database_operation
INFO 08/29/2024 08:42:19 AM Starting POST method and returning data post
INFO 08/29/2024 08:42:19 AM Finishing Post process main
INFO 08/29/2024 08:42:19 AM 127.0.0.1 - - [29/Aug/2024 08:42:19] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 201 - _log
INFO 08/29/2024 08:43:40 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/29/2024 08:43:40 AM [33mPress CTRL+C to quit[0m _log
INFO 08/29/2024 08:43:44 AM Starting main function main
INFO 08/29/2024 08:43:44 AM Post process main
INFO 08/29/2024 08:43:44 AM Starting POST method post
INFO 08/29/2024 08:43:45 AM Connection to Postgres Database successful database_operation
INFO 08/29/2024 08:43:45 AM Verifying if Stock already exists on the database check_stock
INFO 08/29/2024 08:43:45 AM Verification complete check_stock
INFO 08/29/2024 08:43:45 AM Inserting data into Postgres Database update_amount
INFO 08/29/2024 08:43:45 AM Stock AAPL updated successfully with new amount 30.0 update_amount
INFO 08/29/2024 08:43:45 AM Data updated to Postgres Database successfully database_operation
INFO 08/29/2024 08:43:45 AM Starting POST method and returning data post
INFO 08/29/2024 08:43:45 AM Finishing Post process main
INFO 08/29/2024 08:43:45 AM 127.0.0.1 - - [29/Aug/2024 08:43:45] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 201 - _log
INFO 08/29/2024 08:44:09 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/29/2024 08:44:09 AM [33mPress CTRL+C to quit[0m _log
INFO 08/29/2024 08:44:13 AM Starting main function main
INFO 08/29/2024 08:44:13 AM Post process main
INFO 08/29/2024 08:44:13 AM Starting POST method post
INFO 08/29/2024 08:44:14 AM Connection to Postgres Database successful database_operation
INFO 08/29/2024 08:44:14 AM Verifying if Stock already exists on the database check_stock
INFO 08/29/2024 08:44:14 AM Verification complete check_stock
INFO 08/29/2024 08:44:14 AM Inserting data into Postgres Database update_amount
INFO 08/29/2024 08:44:15 AM Stock AAPL updated successfully with new amount 40.0 update_amount
INFO 08/29/2024 08:44:15 AM Data updated to Postgres Database successfully database_operation
INFO 08/29/2024 08:44:15 AM Starting POST method and returning data post
INFO 08/29/2024 08:44:15 AM Finishing Post process main
INFO 08/29/2024 08:44:15 AM 127.0.0.1 - - [29/Aug/2024 08:44:15] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 201 - _log
INFO 08/29/2024 08:45:06 AM [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 _log
INFO 08/29/2024 08:45:06 AM [33mPress CTRL+C to quit[0m _log
INFO 08/29/2024 08:45:08 AM Starting main function main
INFO 08/29/2024 08:45:08 AM Post process main
INFO 08/29/2024 08:45:08 AM Starting POST method post
INFO 08/29/2024 08:45:09 AM Connection to Postgres Database successful database_operation
INFO 08/29/2024 08:45:09 AM Verifying if Stock already exists on the database check_stock
INFO 08/29/2024 08:45:09 AM Verification complete check_stock
INFO 08/29/2024 08:45:09 AM Inserting data into Postgres Database update_amount
INFO 08/29/2024 08:45:09 AM Stock AAPL updated successfully with new amount 50.0 update_amount
INFO 08/29/2024 08:45:09 AM Data updated to Postgres Database successfully database_operation
INFO 08/29/2024 08:45:09 AM Starting POST method and returning data post
INFO 08/29/2024 08:45:09 AM Finishing Post process main
INFO 08/29/2024 08:45:09 AM 127.0.0.1 - - [29/Aug/2024 08:45:09] "[35m[1mPOST /stock/aapl HTTP/1.1[0m" 201 - _log
